name: Pull Request Checks

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**.md'
      - '.gitattributes'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  review_dog_typescript:
    name: ReviewDog Typescript
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-project
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: '.'
          fail_level: 'any'

  review_dog_styles:
    name: ReviewDog Styles
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-project
      - uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_level: 'any'
          reporter: github-pr-review
          stylelint_config: '.stylelintrc.json'
          stylelint_input: '**/*.scss'

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-project
      - run: npm run lint

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-project
      - run: npm run lint:styles

  build_libraries:
    name: Build Libraries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-project
      - run: npm run build:component-library
      - run: npm run build:critter

  build_storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-project
      - run: npm run build:storybook:component-library
      - run: npm run build:storybook:critter

  cypress_component_tests:
    name: Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-project

      - name: Cypress Component Tests
        id: cypress_component_tests
        run: npm run test:cypress

      - name: Upload Cypress screenshots
        if: ${{ always() && steps.cypress_component_tests.outcome == 'failure' }}
        uses: actions/upload-artifact@v6
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

  vitest_unit_tests:
    name: Angular Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - uses: ./.github/actions/setup-project

      - run: npx playwright install

      - name: 'Unit Tests | Component Library'
        id: vitest_unit_tests
        run: npm run test:ci:component-library

      - name: 'Upload Vitest Screenshots | Component Library'
        if: ${{ always() && steps.vitest_unit_tests.outcome == 'failure' }}
        uses: actions/upload-artifact@v6
        with:
          path: projects/component-library/.vitest-attachments
          name: vitest-visual-test-errors-component-library
          if-no-files-found: ignore
          include-hidden-files: true

      - name: 'Unit Tests | Critter'
        id: vitest_unit_tests
        run: npm run test:ci:critter

      - name: 'Upload Vitest Screenshots | Critter'
        if: ${{ always() && steps.vitest_unit_tests.outcome == 'failure' }}
        uses: actions/upload-artifact@v6
        with:
          path: projects/critter/.vitest-attachments
          name: vitest-visual-test-errors-critter
          if-no-files-found: ignore
          include-hidden-files: true

#      - name: Code Coverage Summary Report
#        uses: irongut/CodeCoverageSummary@v1.3.0
#        with:
#          filename: projects/component-library/coverage/clover.xml
#          badge: true
#          fail_below_min: true # Match your Vitest thresholds!
#          format: markdown
#          output: both
